services:
  - type: web
    name: wasteworks
    env: python
    buildCommand: pip install -r dependencies.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: wasteworks-db
          property: connectionString

databases:
  - name: wasteworks-db
    databaseName: wasteworks
    user: wasteworks_user